[input]
    start = "spacebar"
    x = "e"
    y = "q"
    a = "none"
    b = "none"

[input.joystick1]

[input.joystick2]
    left = "mouse-x"
    right = "mouse+x"
    up = "mouse-y"
    down = "mouse+y"